INSERT INTO main.category(name)
VALUES
    ('Aave Tokens'),
    ('Algorand Ecosystem'),
    ('Analytics'),
    ('Arbitrum Ecosystem'),
    ('Arbitrum Nova Ecosystem'),
    ('Artificial Intelligence'),
    ('Asset-backed Tokens'),
    ('Asset Manager'),
    ('Augmented Reality'),
    ('Automated Market Maker (AMM)'),
    ('Avalanche Ecosystem'),
    ('Axie Infinity'),
    ('Big Data'),
    ('Binance Launchpool'),
    ('BNB Chain Ecosystem'),
    ('Business Platform'),
    ('Business Services'),
    ('Cardano Ecosystem'),
    ('Celer Network'),
    ('Celo Ecosystem'),
    ('Centralized Exchange (CEX)'),
    ('Charity'),
    ('CNY Stablecoin'),
    ('Collectibles'),
    ('Communication'),
    ('Compound Tokens'),
    ('Cosmos Ecosystem'),
    ('Cronos Ecosystem'),
    ('Cryptocurrency'),
    ('cToken'),
    ('DaoMaker Ecosystem'),
    ('Decentralized Exchange (DEX)'),
    ('Decentralized Finance (DeFi)'),
    ('DeFi Index'),
    ('Derivatives'),
    ('Eco-Friendly'),
    ('Edgeware Ecosystem'),
    ('Education'),
    ('Elrond Ecosystem'),
    ('Energy'),
    ('Entertainment'),
    ('ETF'),
    ('Eth 2.0 Staking'),
    ('Ethereum Ecosystem'),
    ('Ethereum PoS IOU'),
    ('EthereumPoW Ecosystem'),
    ('Ethereum PoW IOU'),
    ('EUR Stablecoin'),
    ('Exchange-based Tokens'),
    ('Fan Token'),
    ('Fantom Ecosystem'),
    ('Farming-as-a-Service (FaaS)'),
    ('Finance / Banking'),
    ('Fractionalized NFT'),
    ('Gambling'),
    ('Gaming (GameFi'),
    ('GBP Stablecoin'),
    ('Gig Economy'),
    ('Gnosis Chain Ecosystem'),
    ('Gotchiverse'),
    ('Governance'),
    ('Guild and Scholarship'),
    ('Harmony Ecosystem'),
    ('Healthcare'),
    ('HECO Chain Ecosystem'),
    ('Identity'),
    ('Impossible Launchpad'),
    ('Index'),
    ('Infrastructure'),
    ('Insurance'),
    ('Internet Computer Ecosystem'),
    ('Internet of Things (IOT)'),
    ('Interoperability'),
    ('Investment'),
    ('IoTeX Ecosystem'),
    ('KardiaChain Ecosystem'),
    ('Klaytn Ecosystem'),
    ('KRW Stablecoin'),
    ('Launchpad'),
    ('Layer 1'),
    ('Legal'),
    ('Lending/Borrowing'),
    ('Leveraged Token'),
    ('Liquid Staking Governance Tokens'),
    ('Liquid Staking Tokens'),
    ('LP Tokens'),
    ('Manufacturing'),
    ('Marketing'),
    ('Masternodes'),
    ('Media'),
    ('Meme'),
    ('Metagovernance'),
    ('Metaverse'),
    ('Metis Ecosystem'),
    ('MEV Protection'),
    ('Mirrored Assets'),
    ('Moonbeam Ecosystem'),
    ('Moonriver Ecosystem'),
    ('Move To Earn'),
    ('Music'),
    ('Near Protocol Ecosystem'),
    ('NFT'),
    ('NFT Index'),
    ('Niftex Shards'),
    ('Number'),
    ('OEC Ecosystem'),
    ('Ohm Fork'),
    ('Olympus Pro'),
    ('Optimism Ecosystem'),
    ('Options'),
    ('Oracle'),
    ('Perpetuals'),
    ('Play To Earn'),
    ('Polkadot Ecosystem'),
    ('Polygon Ecosystem'),
    ('Prediction Markets'),
    ('Privacy Coins'),
    ('Protocol'),
    ('Real Estate'),
    ('RealT Tokens'),
    ('Rebase Tokens'),
    ('Reddit Points'),
    ('Remittance'),
    ('Retail'),
    ('Seigniorage'),
    ('Smart Contract Platform'),
    ('Social Money'),
    ('Software'),
    ('Solana Ecosystem'),
    ('Sports'),
    ('Stablecoins'),
    ('Storage'),
    ('Structured Products'),
    ('Synthetic Issuer'),
    ('Synths'),
    ('Technology & Science'),
    ('Terra Ecosystem'),
    ('Tezos Ecosystem'),
    ('Tokenized BTC'),
    ('Tokenized Gold'),
    ('Tokenized Products'),
    ('Tokenized Stock'),
    ('TokenSets'),
    ('Tourism'),
    ('USD Stablecoin'),
    ('US Election 2020'),
    ('uTokens'),
    ('Velas Ecosystem'),
    ('Virtual Reality'),
    ('Wallets'),
    ('Wormhole Assets'),
    ('Wrapped-Tokens'),
    ('XDC Ecosystem'),
    ('Yearn Ecosystem'),
    ('Yield Aggregator'),
    ('Yield Farming'),
    ('Zilliqa Ecosystem');