INSERT INTO main.fiat_currency(code, name, symbol, image, last_updated)
VALUES
    ('USD', 'United States Dollar', '$', 'image', NOW()),
    ('AUD', 'Australian Dollar', '$', 'image', NOW()),
    ('BRL', 'Brazilian Real', 'R$', 'image', NOW()),
    ('CAD', 'Canadian Dollar', '$', 'image', NOW()),
    ('CHF', 'Swiss Frank', 'FR', 'image', NOW()),
    ('CLP', 'Chilean Pesco', '$', 'image', NOW()),
    ('CNY', 'Chinese Yuan', '¥', 'image', NOW()),
    ('CZK', 'Czech Koruna', 'KČ', 'image', NOW()),
    ('DKK', 'Danish Krone', 'KR', 'image', NOW()),
    ('EUR', 'Euro', '€', 'image', NOW()),
    ('GBP', 'Pound Sterling', '£', 'image', NOW()),
    ('HKD', 'Hong Kong Dollar', '$', 'image', NOW()),
    ('HUF', 'Hungarian Forint', 'FT', 'image', NOW()),
    ('IDR', 'Indonesian Rupiah', 'RP', 'image', NOW()),
    ('ILS', 'Israeli New Shekel', '₪', 'image', NOW()),
    ('INR', 'Indian Rupee', '₹', 'image', NOW()),
    ('JPY', 'Japanese Yen', '¥', 'image', NOW()),
    ('KRW', 'South Korean Won', '₩', 'image', NOW()),
    ('MXN', 'Mexican Pesco', '$', 'image', NOW()),
    ('MYR', 'Malaysian Ringgit', 'RM', 'image', NOW()),
    ('NOK', 'Norwegian Krone', 'KR', 'image', NOW()),
    ('NZD', 'New Zealand Krone', '$', 'image', NOW()),
    ('PHP', 'Philippine Peso', '₱', 'image', NOW()),
    ('PKR', 'Pakistani Rupee', '₨', 'image', NOW()),
    ('PLN', 'Polish Zloty', 'ZŁ', 'image', NOW()),
    ('RUB', 'Russian Ruble', '₽', 'image', NOW()),
    ('SEK', 'Swedish Krona', 'KR', 'image', NOW()),
    ('SGD', 'Singapore Dollar', 'S$', 'image', NOW()),
    ('THB', 'Thai Baht', '฿', 'image', NOW()),
    ('TRY', 'Turkish Lira', '₺', 'image', NOW()),
    ('TWD', 'New Taiwan Dollar', 'NT$', 'image', NOW()),
    ('ZAR', 'South African Rand', 'R', 'image', NOW()),
    ('VND', 'Vietnamese Dong', '₫', 'image', NOW()),
    ('MAD', 'Moroccan Dirham', 'MAD', 'image', NOW()),
    ('IRR', 'Iranian Rial', 'IRR', 'image', NOW()),
    ('ARS', 'Argentine Peso', 'ARS', 'image', NOW()),
    ('RON', 'Romanian Leu', 'RON', 'image', NOW()),
    ('UAH', 'Ukranian Hryvnia', 'UAH', 'image', NOW()),
    ('NGN', 'Nigerian Naira', 'NGN', 'image', NOW()),
    ('AED', 'United Arab Emirates Dirham', 'AED', 'image', NOW()),
    ('COP', 'Colombian Peso', 'COP', 'image', NOW()),
    ('EGP', 'Egyptian Pound', 'EGP', 'image', NOW()),
    ('SAR', 'Saudi Riyal', 'SAR', 'image', NOW()),
    ('BDT', 'Bangladeshi Taka', 'BDT', 'image', NOW()),
    ('GHS', 'Ghanian Cedi', 'CHS', 'image', NOW()),
    ('BGN', 'Bulgarian Lev', 'BGN', 'image', NOW()),
    ('VES', 'Sovereign Bolivar', 'VES', 'image', NOW());